server:
  port: 8181

logging:
  level:
    adaptor:
      api: DEBUG
    org:
      springframework:
        web: DEBUG


datasource:
  url: jdbc:mysql://localhost:3306/thesisDB
  username: supadmin
  password: root